services:
  mysql-db:
    container_name: mini-ecommerce-db
    image: mysql
    ports:
      - "13306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME}
    networks:
      backend-network:
        ipv4_address: 172.18.0.2
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  django-app:
    container_name: mini-ecommerce-app
    build:
      context: .
    image: yanpin0524/mini-ecommerce-app
    ports:
      - "8000:8000"
    environment:
      - MYSQL_HOST=172.18.0.2
      - MYSQL_PORT=3306
    env_file:
      - .env
    networks:
      - backend-network
    depends_on:
      mysql-db:
        condition: service_healthy

networks:
  backend-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1
