# Generated by Django 4.1 on 2024-03-06 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='user_id',
            new_name='user',
        ),
    ]
